export default {
   base_uri: "http://api.vesal.cn:8000/vesal-jiepao-prod/",
  // base_uri: "http://118.24.119.234:8083/vesal-jiepao-test/",
  initStructLists: [
    {
      FyList: [
        {
          fy_id: 255,
          fy_name: "下肢部",
          parent_id: 3,
          icon: require("./img/struct/20170605100445.png"),
          remark: "模拟正式数据",
          state: "enabled",
          fy_sort: 1,
          fy_grade: 2,
          add_time: 1528099937000
        }
      ],
      code: "FUNCTIONTYPE",
      dict_name: "局部解剖",
      dict_name_en: "jubu",
      StructList: [
        {
          struct_version: "1",
          function_type: "5",
          is_integral: "yes",
          platform: "pc",
          download_count: 99,
          struct_state: "enabled",
          struct_sell_amount: 555,
          first_icon_url: require("./img/struct/20170725090724.png"),
          last_update_time: 1528699977000,
          fy_id: 63,
          is_recommended: "yes",
          fy_name: "下肢部",
          Introduce: "模型介绍",
          visible_identity: "1,2,3,4",
          is_charge: "yes",
          is_hot: "yes",
          struct_id: 262,
          struct_name: "下肢部PC",
          struct_code: "856123132",
          add_time: 1528699977000
        }
      ],
      parent_id: 4,
      dict_value: "RTGZ",
      id: 5,
      sort: 1
    },
    {
      FyList: [
        {
          fy_id: 4,
          fy_name: "整体人",
          parent_id: 2,
          icon: require("./img/struct/20180605101042.png"),
          state: "enabled",
          fy_sort: 1,
          fy_grade: 2,
          add_time: 1529373803000
        },
        {
          fy_id: 5,
          fy_name: "运动系统",
          parent_id: 2,
          icon: require("./img/struct/20170601054226.png"),
          state: "enabled",
          fy_sort: 2,
          fy_grade: 2,
          add_time: 1529373803000
        },
        {
          fy_id: 6,
          fy_name: "内脏学",
          parent_id: 2,
          icon: require("./img/struct/20170601054349.png"),
          state: "enabled",
          fy_sort: 3,
          fy_grade: 2,
          add_time: 1529373803000
        },
        {
          fy_id: 7,
          fy_name: "脉管系统",
          parent_id: 2,
          icon: require("./img/struct/20170601054649.png"),
          state: "enabled",
          fy_sort: 4,
          fy_grade: 2,
          add_time: 1529373803000
        },
        {
          fy_id: 8,
          fy_name: "感觉器",
          parent_id: 2,
          icon: require("./img/struct/20170601054721.png"),
          state: "enabled",
          fy_sort: 5,
          fy_grade: 2,
          add_time: 1529373803000
        },
        {
          fy_id: 9,
          fy_name: "神经系统",
          parent_id: 2,
          icon: require("./img/struct/20170601054740.png"),
          state: "enabled",
          fy_sort: 6,
          fy_grade: 2,
          add_time: 1529373803000
        },
        {
          fy_id: 10,
          fy_name: "内分泌系统",
          parent_id: 2,
          icon: require("./img/struct/20180326112110.png"),
          state: "enabled",
          fy_sort: 7,
          fy_grade: 2,
          add_time: 1529373803000
        }
      ],
      code: "FUNCTIONTYPE",
      dict_name: "人体构造",
      dict_name_en: "gouzao",
      StructList: [
        {
          youke_use: "enabled",
          platform: "pc",
          struct_state: "enabled",
          fy_id: 5,
          fy_name: "运动系统",
          struct_id: 25,
          struct_sort: "1",
          function_type: "5",
          struct_sell_amount: 0,
          first_icon_url: require("./img/struct/SA0101047.jpg"),
          visible_identity: "1,2,3,4",
          struct_name: "全身骨骼系统"
        },
        {
          youke_use: "enabled",
          platform: "pc",
          struct_state: "enabled",
          fy_id: 5,
          fy_name: "运动系统",
          struct_id: 26,
          struct_sort: "2",
          function_type: "5",
          struct_sell_amount: 0,
          first_icon_url: require("./img/struct/SA0102021.jpg"),
          visible_identity: "1,2,3,4",
          struct_name: "全身骨连结"
        },
        {
          youke_use: "enabled",
          platform: "pc",
          struct_state: "enabled",
          fy_id: 5,
          fy_name: "运动系统",
          struct_id: 27,
          struct_sort: "3",
          function_type: "5",
          struct_sell_amount: 0,
          first_icon_url: require("./img/struct/SA0103041.jpg"),
          visible_identity: "1,2,3,4",
          struct_name: "全身肌肉"
        },
        {
          youke_use: "enabled",
          platform: "pc",
          struct_state: "enabled",
          fy_id: 5,
          fy_name: "运动系统",
          Introduce: "标注:SA23",
          struct_id: 7,
          struct_sort: "10",
          function_type: "5",
          struct_sell_amount: 0,
          first_icon_url: require("./img/struct/SA0104007.jpg"),
          visible_identity: "1,2,3,4",
          struct_name: "桡骨和尺骨",
          ab_path: "",

          xml_path: "",
          model_scope: "sa001",
          app_type: "",
          app_id: "",
          app_version: "",
          update_flag: ""
        },
        {
          youke_use: "enabled",
          platform: "pc",
          struct_state: "enabled",
          fy_id: 5,
          fy_name: "运动系统",
          Introduce: "标注:SA26",
          struct_id: 8,
          struct_sort: "11",
          function_type: "5",
          struct_sell_amount: 0,
          first_icon_url: require("./img/struct/SA0104008.jpg"),
          visible_identity: "1,2,3,4",
          struct_name: "眶"
        },
        {
          youke_use: "enabled",
          platform: "pc",
          struct_state: "enabled",
          fy_id: 5,
          fy_name: "运动系统",
          Introduce: "标注:SA30",
          struct_id: 9,
          struct_sort: "12",
          function_type: "5",
          struct_sell_amount: 0,
          first_icon_url: require("./img/struct/SA0104010.jpg"),
          visible_identity: "1,2,3,4",
          struct_name: "股骨"
        },
        {
          youke_use: "enabled",
          platform: "pc",
          struct_state: "enabled",
          fy_id: 5,
          fy_name: "运动系统",
          Introduce: "标注:SA32",
          struct_id: 10,
          struct_sort: "13",
          function_type: "5",
          struct_sell_amount: 0,
          first_icon_url: require("./img/struct/SA0104011.jpg"),
          visible_identity: "1,2,3,4",
          struct_name: "肩胛骨"
        },
        {
          youke_use: "enabled",
          platform: "pc",
          struct_state: "enabled",
          fy_id: 5,
          fy_name: "运动系统",
          Introduce: "标注:SA33",
          struct_id: 11,
          struct_sort: "14",
          function_type: "5",
          struct_sell_amount: 0,
          first_icon_url: require("./img/struct/SA0104012.jpg"),
          visible_identity: "1,2,3,4",
          struct_name: "肱骨"
        },
        {
          youke_use: "enabled",
          platform: "pc",
          struct_state: "enabled",
          fy_id: 5,
          fy_name: "运动系统",
          Introduce: "标注:SA34",
          struct_id: 12,
          struct_sort: "15",
          function_type: "5",
          struct_sell_amount: 0,
          first_icon_url: require("./img/struct/SA0104013.jpg"),
          visible_identity: "1,2,3,4",
          struct_name: "胫骨和腓骨"
        },
        {
          youke_use: "enabled",
          platform: "pc",
          struct_state: "enabled",
          fy_id: 5,
          fy_name: "运动系统",
          Introduce: "标注:SA36",
          struct_id: 13,
          struct_sort: "16",
          function_type: "5",
          struct_sell_amount: 0,
          first_icon_url: require("./img/struct/SA0104015.jpg"),
          visible_identity: "1,2,3,4",
          struct_name: "脊柱整体观"
        },
        {
          youke_use: "enabled",
          platform: "pc",
          struct_state: "enabled",
          fy_id: 5,
          fy_name: "运动系统",
          Introduce: "标注:SA37",
          struct_id: 14,
          struct_sort: "17",
          function_type: "5",
          struct_sell_amount: 0,
          first_icon_url: require("./img/struct/SA0104016.jpg"),
          visible_identity: "1,2,3,4",
          struct_name: "腰椎"
        },
        {
          youke_use: "enabled",
          platform: "pc",
          struct_state: "enabled",
          fy_id: 5,
          fy_name: "运动系统",
          Introduce: "标注:SA40",
          struct_id: 15,
          struct_sort: "18",
          function_type: "5",
          struct_sell_amount: 0,
          first_icon_url: require("./img/struct/SA0104017.jpg"),
          visible_identity: "1,2,3,4",
          struct_name: "舌骨"
        },
        {
          youke_use: "enabled",
          platform: "pc",
          struct_state: "enabled",
          fy_id: 5,
          fy_name: "运动系统",
          Introduce: "标注:SA41",
          struct_id: 16,
          struct_sort: "19",
          function_type: "5",
          struct_sell_amount: 0,
          first_icon_url: require("./img/struct/SA0104018.jpg"),
          visible_identity: "1,2,3,4",
          struct_name: "蝶骨"
        },
        {
          youke_use: "enabled",
          platform: "pc",
          struct_state: "enabled",
          fy_id: 5,
          fy_name: "运动系统",
          Introduce: "标注:SA42",
          struct_id: 17,
          struct_sort: "20",
          function_type: "5",
          struct_sell_amount: 0,
          first_icon_url: require("./img/struct/SA0104019.jpg"),
          visible_identity: "1,2,3,4",
          struct_name: "足骨"
        },
        {
          youke_use: "enabled",
          platform: "pc",
          struct_state: "enabled",
          fy_id: 5,
          fy_name: "运动系统",
          Introduce: "标注:SA43",
          struct_id: 18,
          struct_sort: "21",
          function_type: "5",
          struct_sell_amount: 0,
          first_icon_url: require("./img/struct/SA0104020.jpg"),
          visible_identity: "1,2,3,4",
          struct_name: "锁骨"
        },
        {
          youke_use: "enabled",
          platform: "pc",
          struct_state: "enabled",
          fy_id: 5,
          fy_name: "运动系统",
          Introduce: "标注:SA44",
          struct_id: 19,
          struct_sort: "22",
          function_type: "5",
          struct_sell_amount: 0,
          first_icon_url: require("./img/struct/SA0104021.jpg"),
          visible_identity: "1,2,3,4",
          struct_name: "颅的外面观"
        },
        {
          youke_use: "enabled",
          platform: "pc",
          struct_state: "enabled",
          fy_id: 5,
          fy_name: "运动系统",
          Introduce: "标注:SA45",
          struct_id: 20,
          struct_sort: "23",
          function_type: "5",
          struct_sell_amount: 0,
          first_icon_url: require("./img/struct/SA0104022.jpg"),
          visible_identity: "1,2,3,4",
          struct_name: "颅骨前面观"
        },
        {
          youke_use: "enabled",
          platform: "pc",
          struct_state: "enabled",
          fy_id: 5,
          fy_name: "运动系统",
          Introduce: "标注:SA46",
          struct_id: 21,
          struct_sort: "24",
          function_type: "5",
          struct_sell_amount: 0,
          first_icon_url: require("./img/struct/SA0104023.jpg"),
          visible_identity: "1,2,3,4",
          struct_name: "颈椎"
        },
        {
          youke_use: "enabled",
          platform: "pc",
          struct_state: "enabled",
          fy_id: 5,
          fy_name: "运动系统",
          Introduce: "标注:SA47",
          struct_id: 22,
          struct_sort: "25",
          function_type: "5",
          struct_sell_amount: 0,
          first_icon_url: require("./img/struct/SA0104024.jpg"),
          visible_identity: "1,2,3,4",
          struct_name: "颞骨"
        },
        {
          youke_use: "enabled",
          platform: "pc",
          struct_state: "enabled",
          fy_id: 5,
          fy_name: "运动系统",
          Introduce: "标注:SA49",
          struct_id: 23,
          struct_sort: "26",
          function_type: "5",
          struct_sell_amount: 0,
          first_icon_url: require("./img/struct/SA0104025.jpg"),
          visible_identity: "1,2,3,4",
          struct_name: "骶骨和尾骨"
        },
        {
          youke_use: "enabled",
          platform: "pc",
          struct_state: "enabled",
          fy_id: 5,
          fy_name: "运动系统",
          Introduce: "标注:SA51",
          struct_id: 24,
          struct_sort: "27",
          function_type: "5",
          struct_sell_amount: 0,
          first_icon_url: require("./img/struct/SA0104026.jpg"),
          visible_identity: "1,2,3,4",
          struct_name: "髋骨"
        },
        {
          youke_use: "enabled",
          platform: "pc",
          struct_state: "enabled",
          fy_id: 5,
          fy_name: "运动系统",
          Introduce: "标注:SA16",
          struct_id: 1,
          struct_sort: "4",
          function_type: "5",
          struct_sell_amount: 0,
          first_icon_url: require("./img/struct/SA0104001.jpg"),
          visible_identity: "1,2,3,4",
          struct_name: "上颌骨"
        },
        {
          youke_use: "enabled",
          platform: "pc",
          struct_state: "enabled",
          fy_id: 5,
          fy_name: "运动系统",
          Introduce: "标注:SA17",
          struct_id: 2,
          struct_sort: "5",
          function_type: "5",
          struct_sell_amount: 0,
          first_icon_url: require("./img/struct/SA0104002.jpg"),
          visible_identity: "1,2,3,4",
          struct_name: "下颌骨"
        },
        {
          youke_use: "enabled",
          platform: "pc",
          struct_state: "enabled",
          fy_id: 5,
          fy_name: "运动系统",
          Introduce: "标注:SA19",
          struct_id: 3,
          struct_sort: "6",
          function_type: "5",
          struct_sell_amount: 0,
          first_icon_url: require("./img/struct/SA0104003.jpg"),
          visible_identity: "1,2,3,4",
          struct_name: "寰椎"
        },
        {
          youke_use: "enabled",
          platform: "pc",
          struct_state: "enabled",
          fy_id: 5,
          fy_name: "运动系统",
          Introduce: "标注:SA20",
          struct_id: 4,
          struct_sort: "7",
          function_type: "5",
          struct_sell_amount: 0,
          first_icon_url: require("./img/struct/SA0104004.jpg"),
          visible_identity: "1,2,3,4",
          struct_name: "手骨"
        },
        {
          youke_use: "enabled",
          platform: "pc",
          struct_state: "enabled",
          fy_id: 5,
          fy_name: "运动系统",
          Introduce: "标注:SA21",
          struct_id: 5,
          struct_sort: "8",
          function_type: "5",
          struct_sell_amount: 0,
          first_icon_url: require("./img/struct/SA0104005.jpg"),
          visible_identity: "1,2,3,4",
          struct_name: "枢椎"
        },
        {
          youke_use: "enabled",
          platform: "pc",
          struct_state: "enabled",
          fy_id: 5,
          fy_name: "运动系统",
          Introduce: "标注:SA22",
          struct_id: 6,
          struct_sort: "9",
          function_type: "5",
          struct_sell_amount: 0,
          first_icon_url: require("./img/struct/SA0104006.jpg"),
          visible_identity: "1,2,3,4",
          struct_name: "筛骨"
        }
      ],
      parent_id: 4,
      dict_value: "RTGZ",
      id: 5,
      sort: 1
    },
    {
      FyList: [
        {
          fy_id: 59,
          fy_name: "脉管系统",
          parent_id: 2,
          icon: require("./img/struct/20170601054649.png"),
          remark: "模拟正式数据",
          state: "enabled",
          fy_sort: 1,
          fy_grade: 2,
          add_time: 1528099937000
        }
      ],
      code: "FUNCTIONTYPE",
      dict_name: "测验练习",
      dict_name_en: "lianxi",
      StructList: [
        {
          struct_version: "111",
          function_type: "6",
          is_integral: "yes",
          platform: "pc",
          download_count: 0,
          struct_state: "enabled",
          struct_sell_amount: 0,
          first_icon_url: require("./img/struct/8ed0e8fca09b4009b0b4e6e900fbc411.jpg"),
          last_update_time: 1528699948000,
          fy_id: 59,
          is_recommended: "yes",
          fy_name: "脉管系统",
          Introduce:
            "<meta name='viewport' content='width=device-width,initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no'/><p>112</p>",
          visible_identity: "1,2,3",
          is_charge: "yes",
          is_hot: "yes",
          struct_id: 242,
          struct_name: "测试模型B",
          struct_code: "11",
          add_time: 1528699948000
        }
      ],
      parent_id: 4,
      dict_value: "CYLX",
      id: 6,
      sort: 2
    },
    {
      FyList: [
        {
          fy_id: 60,
          fy_name: "运动系统",
          parent_id: 2,
          icon: require("./img/struct/20170601054226.png"),
          remark: "模拟正式数据",
          state: "enabled",
          fy_sort: 1,
          fy_grade: 2,
          add_time: 1528099937000
        }
      ],
      code: "FUNCTIONTYPE",
      dict_name: "微课课程",
      dict_name_en: "kechen",
      StructList: [
        {
          struct_version: "1",
          function_type: "7",
          is_integral: "yes",
          platform: "pc",
          download_count: 99,
          struct_state: "enabled",
          struct_sell_amount: 555,
          first_icon_url: require("./img/struct/20180506220655.png"),
          last_update_time: 1528699977000,
          fy_id: 60,
          is_recommended: "yes",
          fy_name: "运动系统",
          Introduce: "模型介绍",
          visible_identity: "1,2,3,4",
          is_charge: "yes",
          is_hot: "yes",
          struct_id: 245,
          struct_name: "微课_运动系统01PC",
          struct_code: "856123132",
          add_time: 1528699977000
        },
        {
          struct_version: "1",
          function_type: "7",
          is_integral: "yes",
          platform: "pc",
          download_count: 99,
          struct_state: "enabled",
          struct_sell_amount: 555,
          first_icon_url: require("./img/struct/20180506220719.png"),
          last_update_time: 1528699977000,
          fy_id: 60,
          is_recommended: "yes",
          fy_name: "运动系统",
          Introduce: "模型介绍",
          visible_identity: "1,2,3,4",
          is_charge: "yes",
          is_hot: "yes",
          struct_id: 246,
          struct_name: "微课_运动系统02PC",
          struct_code: "856123132",
          add_time: 1528699977000
        },
        {
          struct_version: "1",
          function_type: "7",
          is_integral: "yes",
          platform: "pc",
          download_count: 99,
          struct_state: "enabled",
          struct_sell_amount: 555,
          first_icon_url: require("./img/struct/20180506220707.png"),
          last_update_time: 1528699977000,
          fy_id: 60,
          is_recommended: "yes",
          fy_name: "运动系统",
          Introduce: "模型介绍",
          visible_identity: "1,2,3,4",
          is_charge: "yes",
          is_hot: "yes",
          struct_id: 247,
          struct_name: "微课_运动系统03PC",
          struct_code: "856123132",
          add_time: 1528699977000
        }
      ],
      parent_id: 4,
      dict_value: "WKKC",
      id: 7,
      sort: 3
    },
    {
      FyList: [
        {
          fy_id: 59,
          fy_name: "颅骨",
          parent_id: 2,
          icon: require("./img/struct/20170601054649.png"),
          remark: "模拟正式数据",
          state: "enabled",
          fy_sort: 1,
          fy_grade: 2,
          add_time: 1528099937000
        }
      ],
      code: "FUNCTIONTYPE",
      dict_name: "互动游戏",
      dict_name_en: "youxi",
      StructList: [],
      parent_id: 4,
      dict_value: "HDYX",
      id: 8,
      sort: 4
    }
  ]
};
